import type { Metadata } from "next";
import {
  ClerkProvider,
} from '@clerk/nextjs'

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppSidebar } from "@/components/app-sidebar";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import TopBarComponent from "@/components/TopBar";
import { Providers } from './providers';
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased w-full h-full flex`}
        >
          <Providers>
            <SidebarProvider>
              <AppSidebar />
              <SidebarInset>
                <TopBarComponent />
                {children}
              </SidebarInset>
            </SidebarProvider>
          </Providers>
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
